### PR TITLE
add third Intel-mode fix to README

### PR DESCRIPTION
**Pull request by bozhodimitrov**
Additional workaround for the Intel-mode and possible Xorg config file misconfiguration.
Also - little refactoring for the links and adding titles for them.

Hi @timrichardson, first of all - thank you for supporting/maintaining this repository!
I added one additional fix that worked out for my particular installation on Asus laptop with Optimus and Ubuntu,

### CODE REVIEW

**Review by timrichardson — COMMENTED** [review]
Can you remove all the bash lines? bash is the default shell in ubuntu and it is not necessary to specify it.

**Review by timrichardson — COMMENTED** [review]
HI, thanks for this. I've already mentioned the bash thing. 
I'm curious about the text you've added to remove /etc/X11/xorg.conf
This file should not exist at all in Ubuntu 18.04. In intel mode, ubuntu does not create an xorg.conf file.
In nvidia mode it does create some config, but not in /etc/X11 ... Ubuntu does not use this directory any longer. It puts files in /usr/share/X11/xorg.conf.d
So I conclude you are not using Ubuntu 18.04. I will only support Ubuntu in these notes.

**Comment by bozhodimitrov** [comment]
The /etc/X11/xorg.conf was a leftover from previous versions of Ubuntu (I actually dist-upgraded "successfully" from 16.04 -> 17.10 -> 18.04 :D and the only thing that broke in between was the switch to Intel-mode).
But with this project, it finally worked ok after this minor problem with the Xorg config and I was so surprised to see my X server booted correctly after renaming it ...

As far as the bash annotation - it just provides information and pigmentation/highlighting to the README.
It is not part of the actual commands, but if you want, I will remove it.
Here is the preview: [README.md](https://github.com/timrichardson/Prime-Ubuntu-18.04/blob/848c8b0ce70acf6000f5b7000a4ed767e74f28b6/README.md)

**Comment by timrichardson** [comment]
Oh, ok. that makes sense (the old xorg file). Can you mention that if you have upgrade from an older ubuntu, you should check for and remove that file? And it would be great to remove the bash lines, I think they are redundant.

**Comment by bozhodimitrov** [comment]
Done.

**Review by timrichardson — APPROVED** [review]
thanks

**Pull request merged**
